export const Colors = {
  PRIMARY: '#003D3A',
  PRIMARY_TEXT: '#FDFBED',

  BACKGROUND: '#FDFBED',
  SURFACE: '#FDFBED',
  BORDER: '#003D3A',

  TEXT_PRIMARY: '#0C1618',
  TEXT_SECONDARY: '#003D3A',

  TOGGLE_ACTIVE_BG: '#003D3A',
  TOGGLE_ACTIVE_BORDER: '#003D3A',
  TOGGLE_ACTIVE_TEXT: '#FDFBED',

  TOGGLE_INACTIVE_BG: '#FADAC7',
  TOGGLE_INACTIVE_BORDER: '#FADAC7',
  TOGGLE_INACTIVE_TEXT: '#0C1618',

  OUTLINE_BUTTON_BORDER: '#003D3A',
  OUTLINE_BUTTON_TEXT: '#003D3A',

  ERROR: '#DC2626',
  DISABLED: '#9CA3AF',
  STEP_INDICATOR: '#003D3A',
} as const;
